backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "site"
    label: "Site Pages"
    files:
      - file: "index.html"
        label: "Homepage (HTML)"
        name: "homepage"
        fields:
          - { label: "HTML", name: "body", widget: "text" }
      - file: "thank-you.html"
        label: "Thank You Page (HTML)"
        name: "thankyou"
        fields:
          - { label: "HTML", name: "body", widget: "text" }
