backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "site"
    label: "Site Files"
    files:
      - label: "Homepage (index.html)"
        name: "homepage"
        file: "index.html"
        fields:
          - label: "Edit HTML"
            name: "body"
            widget: "text"