backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "uploads"
    label: "Uploads"
    folder: "uploads"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "File", name: "file", widget: "file" }
